// src/lib/LabelPreview.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { drawLabel } from './label'
  import { LABEL_SIZES, type LabelSize } from './types'

  interface Props {
    text: string
    labelSize: LabelSize
  }

  let { text, labelSize }: Props = $props()
  let canvas: HTMLCanvasElement

  function render() {
    const size = LABEL_SIZES[labelSize]
    if (!canvas) return
    canvas.width = size.width
    canvas.height = size.height
    const ctx = canvas.getContext('2d')
    if (!ctx) return
    drawLabel(ctx, text, size.width, size.height)
  }

  onMount(() => {
    render()
  })
  $effect(() => {
    render()
  })
</script>

<div class="label-paper">
  <canvas bind:this={canvas} aria-label="Label preview"></canvas>
</div>

// src/lib/LabelPreview.tsx
import { useEffect, useRef } from 'react'
import { drawLabel } from './label'
import { LABEL_SIZES, type LabelSize } from './types'

interface LabelPreviewProps {
  text: string
  labelSize: LabelSize
}

export default function LabelPreview({ text, labelSize }: LabelPreviewProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const size = LABEL_SIZES[labelSize]

  useEffect(() => {
    const canvas = canvasRef.current
    const ctx = canvas?.getContext('2d')
    if (!canvas || !ctx) return

    canvas.width = size.width
    canvas.height = size.height
    drawLabel(ctx, text, size.width, size.height)
  }, [labelSize, size.height, size.width, text])

  return <canvas ref={canvasRef} width={size.width} height={size.height} aria-label="Label preview" />
}
